override_media_options.settings:
  type: config_object
  label: 'Override Media Options settings'
  mapping:
    general_permissions:
      type: boolean
      label: 'Use general permissions.'
    specific_permissions:
      type: boolean
      label: 'Use media type specific permissions.'
